version: '3'

services:
  banco-django:
    image: postgres:12.6
    container_name: banco-django
    restart: unless-stopped
    environment:
      POSTGRES_DB: backlog-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    networks:
      - lccv-network

  backlog:
    container_name: backlog
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: 'desafio.settings'
    build:
      context: backend_final
      dockerfile: ../Dockerfile

    command: bash -c "python manage.py migrate && python manage.py runserver
      0.0.0.0:8000"
    volumes:
      - ./backend_final:/code
    ports:
      - "8000:8000"
    depends_on:
      - banco-django
    networks:
      - lccv-network

networks:
  lccv-network:
    driver: bridge
