# Generated by Django 3.2.9 on 2021-12-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_auto_20211211_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasfiscais',
            name='ano',
        ),
    ]
